second part spring-boot-web
svitlanagalicka/spring-book-store pull request #2
Opened 2024-12-26 16:34 UTC by svitlanagalicka

2024-12-27 07:27 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2024-12-27 07:27 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/intro/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-12-27 07:27 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/intro/controller/BookController.java
> +    @PostMapping
ResponseStatus.CREATED

2024-12-27 07:27 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/intro/mapper/BookMapperImpl.java
> +public class BookMapperImpl implements BookMapper {
Let’s  use MapStruct

2024-12-27 07:27 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +    }
Let’s  add implementation or remove this method

2024-12-27 07:27 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/intro/repository/BookRepositoryImpl.java
> +            return session.get(BookDto.class, id);
you should return Book

2024-12-27 07:27 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/intro/service/BookServiceImpl.java
> +    @Autowired
Redundant annotation

2024-12-29 13:14 UTC, okuzan approved these changes

2025-01-01 15:32 UTC, merged